# Generated by Django 2.2.5 on 2020-02-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text="<a href='#'>修改密码</a>", max_length=128, verbose_name='password'),
        ),
    ]
